### ISSUE TITLE
Whether it is used for kubernetes logs collect

### ISSUE THREAD

**Issue by zhangyuchungit** [clockworm/logback-kafka#2]
Can it be used for log collection in the kubernetes cluster？Does zookeeper need to be in the cluster?

**Comment by clockworm** [comment]
yes,of course support.&nbsp; zookeeper have strong performance, i think no need to deploy cluster.
if server downtime,log will not be collection,so not affect service&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "clockworm/logback-kafka"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月18日(星期五) 上午10:35
收件人:&nbsp;"clockworm/logback-kafka"<logback-kafka@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[clockworm/logback-kafka] Whether it is used for kubernetes logs collect (#2)





 
Can it be used for log collection in the kubernetes cluster？Does zookeeper need to be in the cluster?

**Comment by clockworm** [comment]
yes,of course support. zookeeper have strong performance, i think no need to deploy cluster.
if server downtime,only log will not be collection,then service still provide normal response

**Comment by zhangyuchungit** [comment]
Will there be a resumable upload? If my log service is down,

**Comment by clockworm** [comment]
no problem
